### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale.com#43]
On Monday morning:

- [x] Make repo public (Scott)
- [x] Move repo to modularscale org (Scott)
- [x] Transfer DNS (Tim)
- [ ] Promote the hell out of this thing (4:00)
